modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
    modId="miscblocks"
    version="${file.jarVersion}"
    displayName="Misc Blocks"
    # updateJSONURL="http://myurl.me/"
    # displayURL="http://example.com/"
    # logoFile="miscblocks.png"
    # credits="BJR1984"
    authors="BJR1984"
    description=''' Trap doors that open half each way '''

[[dependencies.miscblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"